# Generated by Django 4.0 on 2021-12-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(auto_now=True)),
                ('entry_time', models.TimeField(auto_now=True)),
                ('exit_datetime', models.DateTimeField(default=None, null=True)),
                ('exit_time', models.TimeField(default=None, null=True)),
                ('student_number', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.room')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'ordering': ['entry_datetime', 'exit_datetime'],
            },
        ),
    ]
